# CI Pipeline configuration for GitHub Actions
name: CI Pipeline
on:
  # Trigger the workflow on push or pull request events for specified branches
  push:
    branches: [main, setup-task]
  pull_request:
    branches: [main]
jobs:
  build-and-check:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      # Check out the repository code to the runner
      uses: actions/checkout@v3
    - name: Set up Python
      # Set up the specified Python version for the job
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      # Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check Python version
      # Verify the Python version installed
      run: python --version
    - name: Run Streamlit app (optional check)
      # Attempt to run the Streamlit app in the background for verification
      run: streamlit run src/main.py --server.enableCORS false --server.port 8501 &